# docker-compose.yml
version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  web:
    build: .
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume:
